//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEConnector.SMEServiceReferenceFDI {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FdiResult", Namespace="http://wistron.com/webservices/")]
    [System.SerializableAttribute()]
    public partial class FdiResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://wistron.com/webservices/", ConfigurationName="SMEServiceReferenceFDI.FDISoap")]
    public interface FDISoap {
        
        // CODEGEN: Generating message contract since element name xmlStr from namespace http://wistron.com/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://wistron.com/webservices/FdiIrT", ReplyAction="*")]
        SMEConnector.SMEServiceReferenceFDI.FdiIrTResponse FdiIrT(SMEConnector.SMEServiceReferenceFDI.FdiIrTRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wistron.com/webservices/FdiIrT", ReplyAction="*")]
        System.Threading.Tasks.Task<SMEConnector.SMEServiceReferenceFDI.FdiIrTResponse> FdiIrTAsync(SMEConnector.SMEServiceReferenceFDI.FdiIrTRequest request);
        
        // CODEGEN: Generating message contract since element name xmlStr from namespace http://wistron.com/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://wistron.com/webservices/FdiGreenT", ReplyAction="*")]
        SMEConnector.SMEServiceReferenceFDI.FdiGreenTResponse FdiGreenT(SMEConnector.SMEServiceReferenceFDI.FdiGreenTRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wistron.com/webservices/FdiGreenT", ReplyAction="*")]
        System.Threading.Tasks.Task<SMEConnector.SMEServiceReferenceFDI.FdiGreenTResponse> FdiGreenTAsync(SMEConnector.SMEServiceReferenceFDI.FdiGreenTRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FdiIrTRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FdiIrT", Namespace="http://wistron.com/webservices/", Order=0)]
        public SMEConnector.SMEServiceReferenceFDI.FdiIrTRequestBody Body;
        
        public FdiIrTRequest() {
        }
        
        public FdiIrTRequest(SMEConnector.SMEServiceReferenceFDI.FdiIrTRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://wistron.com/webservices/")]
    public partial class FdiIrTRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xmlStr;
        
        public FdiIrTRequestBody() {
        }
        
        public FdiIrTRequestBody(string xmlStr) {
            this.xmlStr = xmlStr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FdiIrTResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FdiIrTResponse", Namespace="http://wistron.com/webservices/", Order=0)]
        public SMEConnector.SMEServiceReferenceFDI.FdiIrTResponseBody Body;
        
        public FdiIrTResponse() {
        }
        
        public FdiIrTResponse(SMEConnector.SMEServiceReferenceFDI.FdiIrTResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://wistron.com/webservices/")]
    public partial class FdiIrTResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SMEConnector.SMEServiceReferenceFDI.FdiResult FdiIrTResult;
        
        public FdiIrTResponseBody() {
        }
        
        public FdiIrTResponseBody(SMEConnector.SMEServiceReferenceFDI.FdiResult FdiIrTResult) {
            this.FdiIrTResult = FdiIrTResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FdiGreenTRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FdiGreenT", Namespace="http://wistron.com/webservices/", Order=0)]
        public SMEConnector.SMEServiceReferenceFDI.FdiGreenTRequestBody Body;
        
        public FdiGreenTRequest() {
        }
        
        public FdiGreenTRequest(SMEConnector.SMEServiceReferenceFDI.FdiGreenTRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://wistron.com/webservices/")]
    public partial class FdiGreenTRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xmlStr;
        
        public FdiGreenTRequestBody() {
        }
        
        public FdiGreenTRequestBody(string xmlStr) {
            this.xmlStr = xmlStr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FdiGreenTResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FdiGreenTResponse", Namespace="http://wistron.com/webservices/", Order=0)]
        public SMEConnector.SMEServiceReferenceFDI.FdiGreenTResponseBody Body;
        
        public FdiGreenTResponse() {
        }
        
        public FdiGreenTResponse(SMEConnector.SMEServiceReferenceFDI.FdiGreenTResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://wistron.com/webservices/")]
    public partial class FdiGreenTResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SMEConnector.SMEServiceReferenceFDI.FdiResult FdiGreenTResult;
        
        public FdiGreenTResponseBody() {
        }
        
        public FdiGreenTResponseBody(SMEConnector.SMEServiceReferenceFDI.FdiResult FdiGreenTResult) {
            this.FdiGreenTResult = FdiGreenTResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FDISoapChannel : SMEConnector.SMEServiceReferenceFDI.FDISoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FDISoapClient : System.ServiceModel.ClientBase<SMEConnector.SMEServiceReferenceFDI.FDISoap>, SMEConnector.SMEServiceReferenceFDI.FDISoap {
        
        public FDISoapClient() {
        }
        
        public FDISoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FDISoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FDISoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FDISoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SMEConnector.SMEServiceReferenceFDI.FdiIrTResponse SMEConnector.SMEServiceReferenceFDI.FDISoap.FdiIrT(SMEConnector.SMEServiceReferenceFDI.FdiIrTRequest request) {
            return base.Channel.FdiIrT(request);
        }
        
        public SMEConnector.SMEServiceReferenceFDI.FdiResult FdiIrT(string xmlStr) {
            SMEConnector.SMEServiceReferenceFDI.FdiIrTRequest inValue = new SMEConnector.SMEServiceReferenceFDI.FdiIrTRequest();
            inValue.Body = new SMEConnector.SMEServiceReferenceFDI.FdiIrTRequestBody();
            inValue.Body.xmlStr = xmlStr;
            SMEConnector.SMEServiceReferenceFDI.FdiIrTResponse retVal = ((SMEConnector.SMEServiceReferenceFDI.FDISoap)(this)).FdiIrT(inValue);
            return retVal.Body.FdiIrTResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SMEConnector.SMEServiceReferenceFDI.FdiIrTResponse> SMEConnector.SMEServiceReferenceFDI.FDISoap.FdiIrTAsync(SMEConnector.SMEServiceReferenceFDI.FdiIrTRequest request) {
            return base.Channel.FdiIrTAsync(request);
        }
        
        public System.Threading.Tasks.Task<SMEConnector.SMEServiceReferenceFDI.FdiIrTResponse> FdiIrTAsync(string xmlStr) {
            SMEConnector.SMEServiceReferenceFDI.FdiIrTRequest inValue = new SMEConnector.SMEServiceReferenceFDI.FdiIrTRequest();
            inValue.Body = new SMEConnector.SMEServiceReferenceFDI.FdiIrTRequestBody();
            inValue.Body.xmlStr = xmlStr;
            return ((SMEConnector.SMEServiceReferenceFDI.FDISoap)(this)).FdiIrTAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SMEConnector.SMEServiceReferenceFDI.FdiGreenTResponse SMEConnector.SMEServiceReferenceFDI.FDISoap.FdiGreenT(SMEConnector.SMEServiceReferenceFDI.FdiGreenTRequest request) {
            return base.Channel.FdiGreenT(request);
        }
        
        public SMEConnector.SMEServiceReferenceFDI.FdiResult FdiGreenT(string xmlStr) {
            SMEConnector.SMEServiceReferenceFDI.FdiGreenTRequest inValue = new SMEConnector.SMEServiceReferenceFDI.FdiGreenTRequest();
            inValue.Body = new SMEConnector.SMEServiceReferenceFDI.FdiGreenTRequestBody();
            inValue.Body.xmlStr = xmlStr;
            SMEConnector.SMEServiceReferenceFDI.FdiGreenTResponse retVal = ((SMEConnector.SMEServiceReferenceFDI.FDISoap)(this)).FdiGreenT(inValue);
            return retVal.Body.FdiGreenTResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SMEConnector.SMEServiceReferenceFDI.FdiGreenTResponse> SMEConnector.SMEServiceReferenceFDI.FDISoap.FdiGreenTAsync(SMEConnector.SMEServiceReferenceFDI.FdiGreenTRequest request) {
            return base.Channel.FdiGreenTAsync(request);
        }
        
        public System.Threading.Tasks.Task<SMEConnector.SMEServiceReferenceFDI.FdiGreenTResponse> FdiGreenTAsync(string xmlStr) {
            SMEConnector.SMEServiceReferenceFDI.FdiGreenTRequest inValue = new SMEConnector.SMEServiceReferenceFDI.FdiGreenTRequest();
            inValue.Body = new SMEConnector.SMEServiceReferenceFDI.FdiGreenTRequestBody();
            inValue.Body.xmlStr = xmlStr;
            return ((SMEConnector.SMEServiceReferenceFDI.FDISoap)(this)).FdiGreenTAsync(inValue);
        }
    }
}
